# Generated by Django 4.2.16 on 2024-12-03 00:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'laboratorio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('p_costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('p_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('f_fabricacion', models.DateField(blank=True, default=datetime.date(2024, 12, 2), null=True)),
                ('laboratorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
    ]
