# Generated by Django 4.2.16 on 2024-12-03 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0003_alter_directorgeneral_id_alter_laboratorio_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='directorgeneral',
            table='director',
        ),
    ]
