# Generated by Django 4.2.16 on 2024-12-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0007_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='imagen',
            field=models.URLField(null=True),
        ),
    ]
